#!/usr/bin/env bash
# =============================================================================
# skill-sync test suite
# Tests for BatutaClaude/skills/skill-sync/assets/sync.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC_SCRIPT="$SCRIPT_DIR/sync.sh"

# Test framework
TESTS_RUN=0
TESTS_PASSED=0
TESTS_FAILED=0

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

MOCK_DIR=""

# --- Test helpers ---
assert_eq() {
    local expected="$1"
    local actual="$2"
    local msg="${3:-}"
    if [[ "$expected" == "$actual" ]]; then
        return 0
    else
        echo -e "  ${RED}FAIL${NC}: $msg"
        echo "    Expected: '$expected'"
        echo "    Actual:   '$actual'"
        return 1
    fi
}

assert_contains() {
    local haystack="$1"
    local needle="$2"
    local msg="${3:-}"
    if echo "$haystack" | grep -q "$needle" 2>/dev/null; then
        return 0
    else
        echo -e "  ${RED}FAIL${NC}: $msg"
        echo "    Expected to contain: '$needle'"
        echo "    In: '$haystack'"
        return 1
    fi
}

assert_not_contains() {
    local haystack="$1"
    local needle="$2"
    local msg="${3:-}"
    if ! echo "$haystack" | grep -q "$needle" 2>/dev/null; then
        return 0
    else
        echo -e "  ${RED}FAIL${NC}: $msg"
        echo "    Expected NOT to contain: '$needle'"
        return 1
    fi
}

assert_file_contains() {
    local file="$1"
    local pattern="$2"
    local msg="${3:-}"
    if grep -q "$pattern" "$file" 2>/dev/null; then
        return 0
    else
        echo -e "  ${RED}FAIL${NC}: $msg"
        echo "    File '$file' does not contain: '$pattern'"
        return 1
    fi
}

assert_file_not_contains() {
    local file="$1"
    local pattern="$2"
    local msg="${3:-}"
    if ! grep -q "$pattern" "$file" 2>/dev/null; then
        return 0
    else
        echo -e "  ${RED}FAIL${NC}: $msg"
        echo "    File '$file' should NOT contain: '$pattern'"
        return 1
    fi
}

run_test() {
    local test_name="$1"
    TESTS_RUN=$((TESTS_RUN + 1))
    echo -e "${YELLOW}Running${NC}: $test_name"
    if "$test_name"; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "  ${GREEN}PASS${NC}"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi
}

# --- Mock repo setup ---
setup_mock_repo() {
    MOCK_DIR="$(mktemp -d)"

    # Create BatutaClaude structure
    mkdir -p "$MOCK_DIR/BatutaClaude/skills/test-skill-a"
    mkdir -p "$MOCK_DIR/BatutaClaude/skills/test-skill-b"
    mkdir -p "$MOCK_DIR/BatutaClaude/skills/test-skill-c"
    mkdir -p "$MOCK_DIR/BatutaClaude/agents"

    # Create test skills
    cat > "$MOCK_DIR/BatutaClaude/skills/test-skill-a/SKILL.md" << 'SKILLEOF'
---
name: test-skill-a
description: >
  Test skill A for pipeline.
license: MIT
metadata:
  author: Batuta
  version: "1.0"
  created: "2026-01-01"
  scope: [pipeline]
  auto_invoke: "Testing pipeline actions"
allowed-tools: Read, Edit, Write
---

# Test Skill A
Content here.
SKILLEOF

    cat > "$MOCK_DIR/BatutaClaude/skills/test-skill-b/SKILL.md" << 'SKILLEOF'
---
name: test-skill-b
description: >
  Test skill B for infra.
license: MIT
metadata:
  author: Batuta
  version: "1.0"
  created: "2026-01-01"
  scope: [infra]
  auto_invoke: "Testing infra actions"
allowed-tools: Read, Glob, Grep
---

# Test Skill B
Content here.
SKILLEOF

    cat > "$MOCK_DIR/BatutaClaude/skills/test-skill-c/SKILL.md" << 'SKILLEOF'
---
name: test-skill-c
description: >
  Test skill C for observability.
license: MIT
metadata:
  author: Batuta
  version: "1.0"
  created: "2026-01-01"
  scope: [observability]
  auto_invoke:
    - "Tracking events"
    - "Analyzing patterns"
allowed-tools: Read, Edit, Write, Bash
---

# Test Skill C
Content here.
SKILLEOF

    # Create agent files with delimiters
    cat > "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" << 'AGENTEOF'
# Pipeline Agent

Some content before.

### Skills
<!-- AUTO-GENERATED by skill-sync — do not edit manually -->

| Skill | Auto-invoke | Tools |
|-------|-------------|-------|
| `old-skill` | Old trigger | Old tools |

<!-- END AUTO-GENERATED -->

Some content after.
AGENTEOF

    cat > "$MOCK_DIR/BatutaClaude/agents/infra-agent.md" << 'AGENTEOF'
# Infra Agent

### Skills
<!-- AUTO-GENERATED by skill-sync — do not edit manually -->

| Skill | Auto-invoke | Tools |
|-------|-------------|-------|

<!-- END AUTO-GENERATED -->
AGENTEOF

    cat > "$MOCK_DIR/BatutaClaude/agents/observability-agent.md" << 'AGENTEOF'
# Observability Agent

### Skills
<!-- AUTO-GENERATED by skill-sync — do not edit manually -->

| Skill | Auto-invoke | Tools |
|-------|-------------|-------|

<!-- END AUTO-GENERATED -->
AGENTEOF

    # Create CLAUDE.md with delimiters
    cat > "$MOCK_DIR/BatutaClaude/CLAUDE.md" << 'CLAUDEEOF'
# Instructions

Some rules here.

### Available Skills
<!-- AUTO-GENERATED by skill-sync — do not edit manually -->

| Skill | Scope | Auto-invoke |
|-------|-------|-------------|

<!-- END AUTO-GENERATED -->

### Planned project skills
Backend: temporal-worker
CLAUDEEOF
}

teardown_mock_repo() {
    [[ -n "$MOCK_DIR" && -d "$MOCK_DIR" ]] && rm -rf "$MOCK_DIR"
    MOCK_DIR=""
}

# =============================================================================
# TESTS
# =============================================================================

# --- Flag tests ---

test_dry_run_no_changes() {
    setup_mock_repo
    local before
    before="$(cat "$MOCK_DIR/BatutaClaude/CLAUDE.md")"

    # Run sync in dry-run
    bash "$SYNC_SCRIPT" --dry-run 2>/dev/null || true

    local after
    after="$(cat "$MOCK_DIR/BatutaClaude/CLAUDE.md")"
    assert_eq "$before" "$after" "CLAUDE.md should not change in dry-run"

    teardown_mock_repo
}

test_scope_filter() {
    setup_mock_repo

    # Override SCRIPT_DIR context by cd'ing
    cd "$MOCK_DIR/BatutaClaude/skills/skill-sync/assets" 2>/dev/null || cd "$MOCK_DIR"

    bash "$SYNC_SCRIPT" --scope pipeline 2>/dev/null || true

    # Pipeline agent should be updated
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "test-skill-a" \
        "Pipeline agent should have test-skill-a"

    # Infra agent should NOT be updated (scope filter)
    assert_file_not_contains "$MOCK_DIR/BatutaClaude/agents/infra-agent.md" "test-skill-b" \
        "Infra agent should NOT be updated with scope filter"

    teardown_mock_repo
}

# --- Extraction tests ---

test_extract_field_string() {
    setup_mock_repo
    local skill_file="$MOCK_DIR/BatutaClaude/skills/test-skill-a/SKILL.md"

    # Source the extract functions (they're in sync.sh)
    # We'll use bash to call them
    local name
    name=$(bash -c "
        $(declare -f 2>/dev/null || true)
        source '$SYNC_SCRIPT' 2>/dev/null || true
        extract_field '$skill_file' 'name'
    " 2>/dev/null) || name=""

    # Fallback: extract directly with awk
    if [[ -z "$name" ]]; then
        name=$(awk '
            /^---$/ { in_front++; next }
            in_front == 1 && /^name:/ {
                val = $0; sub(/^name:[ ]*/, "", val)
                gsub(/^["'"'"'"]|["'"'"'"]$/, "", val)
                gsub(/^[ \t]+|[ \t]+$/, "", val)
                print val; exit
            }
            in_front >= 2 { exit }
        ' "$skill_file")
    fi

    assert_eq "test-skill-a" "$name" "Should extract name field"
    teardown_mock_repo
}

test_extract_metadata_string() {
    setup_mock_repo
    local skill_file="$MOCK_DIR/BatutaClaude/skills/test-skill-a/SKILL.md"

    local scope
    scope=$(awk '
        /^---$/ { in_front++; next }
        in_front == 1 {
            if (/^metadata:/) { in_meta = 1; next }
            if (in_meta && /^[^ ]/) { in_meta = 0 }
            if (in_meta && /^  scope:/) {
                val = $0; sub(/^  scope:[ ]*/, "", val)
                gsub(/^[ \t]+|[ \t]+$/, "", val)
                print val; exit
            }
        }
        in_front >= 2 { exit }
    ' "$skill_file")

    assert_eq "[pipeline]" "$scope" "Should extract metadata.scope"
    teardown_mock_repo
}

test_extract_metadata_list() {
    setup_mock_repo
    local skill_file="$MOCK_DIR/BatutaClaude/skills/test-skill-c/SKILL.md"

    local auto_invoke
    auto_invoke=$(awk '
        /^---$/ { in_front++; next }
        in_front == 1 {
            if (/^metadata:/) { in_meta = 1; next }
            if (in_meta && /^[^ ]/) { in_meta = 0 }
            if (in_meta && /^  auto_invoke:/) {
                val = $0; sub(/^  auto_invoke:[ ]*/, "", val)
                gsub(/^[ \t]+|[ \t]+$/, "", val)
                if (val == "" || val == ">") {
                    list_items = ""
                    while (getline > 0) {
                        if (/^    - /) {
                            item = $0; sub(/^    - ["'"'"'"'"'"'"]?/, "", item)
                            sub(/["'"'"'"'"'"'"]?$/, "", item)
                            gsub(/^[ \t]+|[ \t]+$/, "", item)
                            if (list_items != "") list_items = list_items "|"
                            list_items = list_items item
                        } else { break }
                    }
                    if (list_items != "") print list_items
                } else {
                    print val
                }
                exit
            }
        }
        in_front >= 2 { exit }
    ' "$skill_file")

    assert_contains "$auto_invoke" "Tracking events" "Should contain first list item"
    assert_contains "$auto_invoke" "Analyzing patterns" "Should contain second list item"
    teardown_mock_repo
}

# --- Generation tests ---

test_agent_table_format() {
    setup_mock_repo

    bash "$SYNC_SCRIPT" 2>/dev/null || true

    # Check pipeline agent has correct table format
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "test-skill-a" \
        "Pipeline agent should contain test-skill-a"
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "Testing pipeline actions" \
        "Pipeline agent should contain auto-invoke text"
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "Read, Edit, Write" \
        "Pipeline agent should contain tools"

    teardown_mock_repo
}

test_claude_table_format() {
    setup_mock_repo

    bash "$SYNC_SCRIPT" 2>/dev/null || true

    # CLAUDE.md should have all 3 skills
    assert_file_contains "$MOCK_DIR/BatutaClaude/CLAUDE.md" "test-skill-a" \
        "CLAUDE.md should contain test-skill-a"
    assert_file_contains "$MOCK_DIR/BatutaClaude/CLAUDE.md" "test-skill-b" \
        "CLAUDE.md should contain test-skill-b"
    assert_file_contains "$MOCK_DIR/BatutaClaude/CLAUDE.md" "test-skill-c" \
        "CLAUDE.md should contain test-skill-c"
    assert_file_contains "$MOCK_DIR/BatutaClaude/CLAUDE.md" "pipeline" \
        "CLAUDE.md should contain scope pipeline"

    teardown_mock_repo
}

test_deterministic_ordering() {
    setup_mock_repo

    bash "$SYNC_SCRIPT" 2>/dev/null || true
    local run1
    run1="$(cat "$MOCK_DIR/BatutaClaude/CLAUDE.md")"

    bash "$SYNC_SCRIPT" 2>/dev/null || true
    local run2
    run2="$(cat "$MOCK_DIR/BatutaClaude/CLAUDE.md")"

    assert_eq "$run1" "$run2" "Two runs should produce identical output"
    teardown_mock_repo
}

# --- Replacement tests ---

test_section_replacement() {
    setup_mock_repo

    bash "$SYNC_SCRIPT" 2>/dev/null || true

    # Old content should be gone
    assert_file_not_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "old-skill" \
        "Old skill should be replaced"
    # New content should be there
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "test-skill-a" \
        "New skill should be present"

    teardown_mock_repo
}

test_preserves_surrounding() {
    setup_mock_repo

    bash "$SYNC_SCRIPT" 2>/dev/null || true

    # Content before delimiters should be preserved
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "Some content before" \
        "Content before should be preserved"
    # Content after delimiters should be preserved
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "Some content after" \
        "Content after should be preserved"
    # CLAUDE.md planned skills should be preserved
    assert_file_contains "$MOCK_DIR/BatutaClaude/CLAUDE.md" "Planned project skills" \
        "Content after delimiters in CLAUDE.md should be preserved"

    teardown_mock_repo
}

test_idempotent() {
    setup_mock_repo

    bash "$SYNC_SCRIPT" 2>/dev/null || true
    local after_first
    after_first="$(cat "$MOCK_DIR/BatutaClaude/CLAUDE.md")"

    bash "$SYNC_SCRIPT" 2>/dev/null || true
    local after_second
    after_second="$(cat "$MOCK_DIR/BatutaClaude/CLAUDE.md")"

    assert_eq "$after_first" "$after_second" "Idempotent: 2 runs = same result"

    teardown_mock_repo
}

test_missing_section_warns() {
    setup_mock_repo

    # Remove delimiters from an agent
    cat > "$MOCK_DIR/BatutaClaude/agents/infra-agent.md" << 'EOF'
# Infra Agent
No delimiters here.
EOF

    local output
    output="$(bash "$SYNC_SCRIPT" 2>&1)" || true

    assert_contains "$output" "WARN" "Should warn about missing delimiters"
    teardown_mock_repo
}

# --- Validation tests ---

test_missing_scope_reports() {
    setup_mock_repo

    # Create a skill without scope
    mkdir -p "$MOCK_DIR/BatutaClaude/skills/bad-skill"
    cat > "$MOCK_DIR/BatutaClaude/skills/bad-skill/SKILL.md" << 'EOF'
---
name: bad-skill
description: No scope.
license: MIT
metadata:
  author: Batuta
  version: "1.0"
  created: "2026-01-01"
allowed-tools: Read
---
EOF

    local output
    output="$(bash "$SYNC_SCRIPT" 2>&1)" || true
    assert_contains "$output" "missing metadata.scope" "Should report missing scope"

    teardown_mock_repo
}

test_missing_auto_invoke_reports() {
    setup_mock_repo

    mkdir -p "$MOCK_DIR/BatutaClaude/skills/bad-skill2"
    cat > "$MOCK_DIR/BatutaClaude/skills/bad-skill2/SKILL.md" << 'EOF'
---
name: bad-skill2
description: No auto_invoke.
license: MIT
metadata:
  author: Batuta
  version: "1.0"
  created: "2026-01-01"
  scope: [pipeline]
allowed-tools: Read
---
EOF

    local output
    output="$(bash "$SYNC_SCRIPT" 2>&1)" || true
    assert_contains "$output" "missing metadata.auto_invoke" "Should report missing auto_invoke"

    teardown_mock_repo
}

test_missing_allowed_tools_reports() {
    setup_mock_repo

    mkdir -p "$MOCK_DIR/BatutaClaude/skills/bad-skill3"
    cat > "$MOCK_DIR/BatutaClaude/skills/bad-skill3/SKILL.md" << 'EOF'
---
name: bad-skill3
description: No tools.
license: MIT
metadata:
  author: Batuta
  version: "1.0"
  created: "2026-01-01"
  scope: [pipeline]
  auto_invoke: "Testing"
---
EOF

    local output
    output="$(bash "$SYNC_SCRIPT" 2>&1)" || true
    assert_contains "$output" "missing allowed-tools" "Should report missing allowed-tools"

    teardown_mock_repo
}

test_scope_without_agent_reports() {
    setup_mock_repo

    # Create a skill with a scope that has no agent
    mkdir -p "$MOCK_DIR/BatutaClaude/skills/orphan-skill"
    cat > "$MOCK_DIR/BatutaClaude/skills/orphan-skill/SKILL.md" << 'EOF'
---
name: orphan-skill
description: Orphan.
license: MIT
metadata:
  author: Batuta
  version: "1.0"
  created: "2026-01-01"
  scope: [backend]
  auto_invoke: "Backend stuff"
allowed-tools: Read
---
EOF

    local output
    output="$(bash "$SYNC_SCRIPT" 2>&1)" || true
    assert_contains "$output" "No agent file for scope" "Should report scope without agent"

    teardown_mock_repo
}

# --- Integration tests ---

test_full_sync_pipeline() {
    setup_mock_repo

    bash "$SYNC_SCRIPT" 2>/dev/null || true

    # Verify all agents updated
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "test-skill-a" \
        "Pipeline agent updated"
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/infra-agent.md" "test-skill-b" \
        "Infra agent updated"
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/observability-agent.md" "test-skill-c" \
        "Observability agent updated"

    # Verify CLAUDE.md has all skills
    local claude_content
    claude_content="$(cat "$MOCK_DIR/BatutaClaude/CLAUDE.md")"
    assert_contains "$claude_content" "test-skill-a" "CLAUDE.md has skill a"
    assert_contains "$claude_content" "test-skill-b" "CLAUDE.md has skill b"
    assert_contains "$claude_content" "test-skill-c" "CLAUDE.md has skill c"
    assert_contains "$claude_content" "pipeline" "CLAUDE.md has pipeline scope"
    assert_contains "$claude_content" "infra" "CLAUDE.md has infra scope"
    assert_contains "$claude_content" "observability" "CLAUDE.md has observability scope"

    teardown_mock_repo
}

test_new_skill_added() {
    setup_mock_repo

    # Initial sync
    bash "$SYNC_SCRIPT" 2>/dev/null || true

    # Add a new skill
    mkdir -p "$MOCK_DIR/BatutaClaude/skills/new-skill"
    cat > "$MOCK_DIR/BatutaClaude/skills/new-skill/SKILL.md" << 'EOF'
---
name: new-skill
description: Brand new.
license: MIT
metadata:
  author: Batuta
  version: "1.0"
  created: "2026-02-21"
  scope: [pipeline]
  auto_invoke: "New functionality"
allowed-tools: Read, Edit
---
EOF

    # Re-sync
    bash "$SYNC_SCRIPT" 2>/dev/null || true

    # Verify new skill appears
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/pipeline-agent.md" "new-skill" \
        "New skill should appear in pipeline agent"
    assert_file_contains "$MOCK_DIR/BatutaClaude/CLAUDE.md" "new-skill" \
        "New skill should appear in CLAUDE.md"

    teardown_mock_repo
}

test_list_auto_invoke_display() {
    setup_mock_repo

    bash "$SYNC_SCRIPT" 2>/dev/null || true

    # test-skill-c has list auto_invoke — should display joined with "; "
    assert_file_contains "$MOCK_DIR/BatutaClaude/agents/observability-agent.md" "Tracking events" \
        "List auto_invoke should display first item"

    teardown_mock_repo
}

# =============================================================================
# RUN ALL TESTS
# =============================================================================
echo "==================================="
echo "  skill-sync test suite"
echo "==================================="
echo ""

run_test test_dry_run_no_changes
run_test test_extract_field_string
run_test test_extract_metadata_string
run_test test_extract_metadata_list
run_test test_agent_table_format
run_test test_claude_table_format
run_test test_deterministic_ordering
run_test test_section_replacement
run_test test_preserves_surrounding
run_test test_idempotent
run_test test_missing_section_warns
run_test test_missing_scope_reports
run_test test_missing_auto_invoke_reports
run_test test_missing_allowed_tools_reports
run_test test_scope_without_agent_reports
run_test test_full_sync_pipeline
run_test test_new_skill_added
run_test test_list_auto_invoke_display

echo ""
echo "==================================="
echo -e "  Results: ${GREEN}$TESTS_PASSED passed${NC}, ${RED}$TESTS_FAILED failed${NC} / $TESTS_RUN total"
echo "==================================="

[[ $TESTS_FAILED -eq 0 ]] && exit 0 || exit 1
